services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ./frontend/dist/assets:/app/mysite/static
      - ./frontend/dist/index.html:/app/mysite/templates/vue_index.html
      - .:/app

  node:
    image: node:20
    environment:
      - UID=${UID}
      - GID=${GID}
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: >
            sh -c "npm run build && chown -R ${UID:-1000}:${GID:-1000} /frontend/dist"
