services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ./frontend/dist/assets:/app/mysite/static
      - ./frontend/dist:/app/mysite/templates/vue_build
      - .:/app

  node:
    image: node:20
    working_dir: /frontend
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ./frontend:/frontend
    command: >
      sh -c "npm run build"
